// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "DD HTTPS server in Go with Swagger endpoints definition.",
    "title": "go-rest-api",
    "version": "0.1.0"
  },
  "paths": {
    "/dd/scanall": {
      "post": {
        "description": "scans all unread mails!",
        "responses": {
          "200": {
            "description": "Returns the greeting.",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Invalid characters were provided."
          }
        }
      }
    },
    "/dd/scanone": {
      "post": {
        "description": "scans given email thread!",
        "responses": {
          "200": {
            "description": "Returns the greeting.",
            "schema": {
              "type": "object",
              "properties": {
                "action": {
                  "description": "action",
                  "type": "object",
                  "properties": {
                    "notification": {
                      "description": "notification",
                      "type": "object",
                      "properties": {
                        "text": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid characters were provided."
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "DD HTTPS server in Go with Swagger endpoints definition.",
    "title": "go-rest-api",
    "version": "0.1.0"
  },
  "paths": {
    "/dd/scanall": {
      "post": {
        "description": "scans all unread mails!",
        "responses": {
          "200": {
            "description": "Returns the greeting.",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Invalid characters were provided."
          }
        }
      }
    },
    "/dd/scanone": {
      "post": {
        "description": "scans given email thread!",
        "responses": {
          "200": {
            "description": "Returns the greeting.",
            "schema": {
              "type": "object",
              "properties": {
                "action": {
                  "description": "action",
                  "type": "object",
                  "properties": {
                    "notification": {
                      "description": "notification",
                      "type": "object",
                      "properties": {
                        "text": {
                          "type": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid characters were provided."
          }
        }
      }
    }
  },
  "definitions": {
    "PostDdScanoneOKBodyAction": {
      "description": "action",
      "type": "object",
      "properties": {
        "notification": {
          "description": "notification",
          "type": "object",
          "properties": {
            "text": {
              "type": "string"
            }
          }
        }
      }
    },
    "PostDdScanoneOKBodyActionNotification": {
      "description": "notification",
      "type": "object",
      "properties": {
        "text": {
          "type": "string"
        }
      }
    }
  }
}`))
}
