// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostDdScanoneOKCode is the HTTP code returned for type PostDdScanoneOK
const PostDdScanoneOKCode int = 200

/*
PostDdScanoneOK Returns the greeting.

swagger:response postDdScanoneOK
*/
type PostDdScanoneOK struct {

	/*
	  In: Body
	*/
	Payload *PostDdScanoneOKBody `json:"body,omitempty"`
}

// NewPostDdScanoneOK creates PostDdScanoneOK with default headers values
func NewPostDdScanoneOK() *PostDdScanoneOK {

	return &PostDdScanoneOK{}
}

// WithPayload adds the payload to the post dd scanone o k response
func (o *PostDdScanoneOK) WithPayload(payload *PostDdScanoneOKBody) *PostDdScanoneOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post dd scanone o k response
func (o *PostDdScanoneOK) SetPayload(payload *PostDdScanoneOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDdScanoneOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostDdScanoneBadRequestCode is the HTTP code returned for type PostDdScanoneBadRequest
const PostDdScanoneBadRequestCode int = 400

/*
PostDdScanoneBadRequest Invalid characters were provided.

swagger:response postDdScanoneBadRequest
*/
type PostDdScanoneBadRequest struct {
}

// NewPostDdScanoneBadRequest creates PostDdScanoneBadRequest with default headers values
func NewPostDdScanoneBadRequest() *PostDdScanoneBadRequest {

	return &PostDdScanoneBadRequest{}
}

// WriteResponse to the client
func (o *PostDdScanoneBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
