// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostDdScanallOKCode is the HTTP code returned for type PostDdScanallOK
const PostDdScanallOKCode int = 200

/*
PostDdScanallOK Returns the greeting.

swagger:response postDdScanallOK
*/
type PostDdScanallOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostDdScanallOK creates PostDdScanallOK with default headers values
func NewPostDdScanallOK() *PostDdScanallOK {

	return &PostDdScanallOK{}
}

// WithPayload adds the payload to the post dd scanall o k response
func (o *PostDdScanallOK) WithPayload(payload string) *PostDdScanallOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post dd scanall o k response
func (o *PostDdScanallOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDdScanallOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// PostDdScanallBadRequestCode is the HTTP code returned for type PostDdScanallBadRequest
const PostDdScanallBadRequestCode int = 400

/*
PostDdScanallBadRequest Invalid characters were provided.

swagger:response postDdScanallBadRequest
*/
type PostDdScanallBadRequest struct {
}

// NewPostDdScanallBadRequest creates PostDdScanallBadRequest with default headers values
func NewPostDdScanallBadRequest() *PostDdScanallBadRequest {

	return &PostDdScanallBadRequest{}
}

// WriteResponse to the client
func (o *PostDdScanallBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
